# Basic config
baseURL = "https://subinbg.github.io"
# theme = "hugo-simple"
languageCode = "en"                # zh-Hans
title = "Personal Homepage"
copyright = "© 2024 Subeen Pang"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
description = "Personal Homepage"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
[params.author]
name = "Subeen Pang"
email = "subinbg@users.noreply.github.com"

# [[menu.main]]
# name = "Home"
# pageRef = "/"
# weight = 10
# [[menu.main]]
# name = "Blog"
# pageRef = "/blog"
# weight = 20

# [services.rss]
# limit = 42

[outputs]
# Disable section RSS
section = ["html"]
