# docker system prune -a # CAUTION! This will remove ALL docker images
FROM mcr.microsoft.com/devcontainers/base:jammy
RUN sudo apt update && sudo apt install build-essential -y --no-install-recommends